### ISSUE TITLE
How to use in LInux

### ISSUE THREAD

**Issue by vk0xOrg** [kennytm/shary#1]
how could one use shary on Linux?
I've tried:
`cargo build`
but it failed with Error:
`Some errors occurred: E0432, E0658.`

Here is a [pastebin](https://bin.nixnet.services/?aa7cd2720bd3fd26#7X78uq4sAw9W9rmvbQ9yu95ybj5PkRm59GvnEmWLuA5N) with full error

**Comment by kennytm** [comment]
@vk0xOrg Hi. This program depends on the latest Rust stable release (1.41). Please install rustc using `rustup` instead of the one provided by the distro.

**Comment by vk0xOrg** [comment]
Works, thank you.
